### ISSUE TITLE
Fix flyout menus

### ISSUE THREAD

**Issue by brinkdinges** [CAD-Booster/solidworks-api#11]
Issues with functionality:
- [x]   Flyouts are not working yet
- [x]   It seems to remember toolbar settings, so if you run it twice, only some things are set as you ask which isn't consistent.

There's a lot to improve with these menus:
- [x] The code is hard to understand
- [x] The terms are hard to understand
- [x] CommandManagerItem has three boolean properties like VisibleForAssemblies. Can we combine these to use the single ModelTypes property in the methods to add the items?
- [x] It uses integers for IDs and styles, which can be confusing. 
- [x] Are styles the same as TabView?
- [x] swCommandTabButtonFlyoutStyle_e and swCommandTabButtonTextDisplay_e are combined in CommandManagerGroup.AddItemsToTab is weird, but it looks like that is meant to happen.

**Comment by KC-MarKamp** [comment]
Fixed subtasks 7 and 8 with commit: 4b3054dabbdba90d60d3d72a2c90c9ff700733f8

**Comment by KC-MarKamp** [comment]
I managed to get the flyouts to be visible in the toolbar, but when I hover over them or click the flyout, an error message pops up with the following text: "An invalid argument was encountered."

**Comment by brinkdinges** [comment]
I copied this code and used a cleaned-up version to create a command manager tab, buttons and flyouts.
https://help.solidworks.com/2023/english/api/sldworksapi/Create_Flyouts_in_the_CommandManager_Example_CSharp.htm

It creates two flyouts. The first one contains both items that are already on the left of it. That's the dropdown from #39.
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/2fdc1f2c-da62-49a7-bc4b-ac37d0ce06eb)

The second flyout is more useful since it contains different items. These items are added when you click the flyouts, which I'm not sure is necessary. They call it a _dynamic flyout_. 

To create it. 
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/dc2a3829-7f4c-4345-8de4-b706af9b18ab)

Create a tab box and separator. I'm not sure this is necessary:
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/c97ec1a8-4f29-4bc3-8a11-e785961cc78c)

On the click callback, add the items. Make sure the icons are valid or it won't work and AddCommandItem will return -1.
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/ddfa14e1-cbe5-42a0-81a5-e669ba27a8df)

**Comment by brinkdinges** [comment]
Creating the new tab box was indeed not necessary. You can add all of these items to the same tab box:

![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/3e2a39c3-6236-4cd2-b68e-d6eece70c0af)

The result:
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/a44be3d7-455a-46e1-abf5-7d48946ab970)

**Comment by brinkdinges** [comment]
But adding the flyout items at runtime is necessary! You can add them directly after you create the flyout and the flyout now says it contains two buttons.

![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/11b0c781-fcfc-4696-98e1-a972160096a9)

But this just doesn't work, you always get this useless error:
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/9e2a7b41-4018-4a9b-a72c-6fb090a0b42e)

You have to remove, then add the buttons **in the flyout callback function** 
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/38e3d9ab-5831-45ac-86fc-23d7a24a2ae0)

But you only need to do this once, it seems. This also works:
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/442a0749-88ae-4234-87ca-a002cfd587c4)

SolidWorks give only a **tiny** hint in the documentation:
https://help.solidworks.com/2023/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.IFlyoutGroup~AddCommandItem.html
![image](https://github.com/CAD-Booster/solidworks-api/assets/15387410/0877d28a-e376-4c02-9f2f-f56a313c8459)

Since we create all tabs and toolbars at runtime, I understand why I never got this hint.

**Comment by brinkdinges** [comment]
Finally, finally fixed with 95632a226b7a2728e8ae2e1bf4847fe914890c51 🎉
