### ISSUE TITLE
Replace using random IDs for toolbars

### ISSUE THREAD

**Issue by brinkdinges** [CAD-Booster/solidworks-api#12]
We seem to be leaving traces of old toolbars behind. I think that's because we create a random ID for each toolbar every time, or we start from zero every time. Can we let the user choose a better ID instead?

**Comment by KC-MarKamp** [comment]
Toolbar IDs we assign in code will not be in the registry with the same ID. They may be encoded. Solidworks seems always to give 59000+ numbers to our 'uiCustomApiToolbars', for example, '`uiCustomApiToolbars_c59424`' Regedit place: `HKEY_CURRENT_USER\Software\SolidWorks\SOLIDWORKS 2022\User Interface\Toolbars\` but will also be assigned within the underlying AssemblyTool, PartTool, and DrawingTools key.

**Comment by brinkdinges** [comment]
I found two references to the registry in the API docs:

CreateCommandGroup2: 

> Call [ICommandManager::GetGroupDataFromRegistry](https://help.solidworks.com/2018/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.ICommandManager~GetGroupDataFromRegistry.html) or [ICommandManager::IGetGroupDataFromRegistry](https://help.solidworks.com/2018/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.ICommandManager~IGetGroupDataFromRegistry.html) before calling this method to determine how to set IgnorePreviousVersion. Set IgnorePreviousVersion to true to prevent SOLIDWORKS from saving the current toolbar setting to the registry, even if there is no previous version.

RemoveCommandGroup2:
> RuntimeOnly
True to remove the CommandGroup , saving its toolbar information in the registry; false to remove both the CommandGroup and its toolbar information in the registry

**Comment by brinkdinges** [comment]
I tried adding a toolbar, then shutting down my add-in. The toolbar still disappears, even though I commented out:
- RemoveCommandGroup2 calls
- CommandManager.Dispose 
- CommandManagerTab.Dispose
- CommandManagerGroup.Dispose

I see no Dispose calls to SolidDnaObject or SharedSolidDnaObject anymore, yet the toolbar still disappears.

**Next test**
I am building one toolbar, but two appear. The second one is a previous version. Both also disappear when I shut down the add-in, so SolidWorks knows that they belong to this add-in.

**Comment by brinkdinges** [comment]
SolidWorks API support says these toolbars are not saved in the registry by default and how we do it in SolidDNA. So how we currently do it is correct.

We haven't figured out why my installations are full of old toolbars, though. We have not found where this data is saved.

**Comment by brinkdinges** [comment]
Toolbar data is saved in the Windows Registry in HKEY_CURRENT_USER\Software\Solidworks\SolidWorks 20xx\User interface\

In the CommandManager folder, there are three folders: AssyContext. DrwContext, PartContext. Each of these has a bunch of folders like "Tab01", each folder has a value called "Tab Props". If the Tab Props value contains a name, it's a custom toolbar that you created at some point. You can delete these while solidworks is closed to clean them up. I also had a bunch command manager tabs with no name in solidworks,  these were caused by empty Tab0x folders in the Registry.

Task panes that you created appear in User interface\TaskPane

Toobars appear in User interface\Toolbars in the AssemblyTool, DrawingTool or PartTool subfolder.
