### ISSUE TITLE
Convert all projects to SDK style

### ISSUE THREAD

**Issue by brinkdinges** [CAD-Booster/solidworks-api#16]

**Comment by brinkdinges** [comment]
If anyone can start a branch and run try-convert on all projects in the repo that are not SDK-style yet, I'd be very grateful. Try-convert seems to have a bug and I cannot get it to run anymore. I can clean up the projects afterwards.

More info: https://github.com/dotnet/try-convert
The issue: https://github.com/dotnet/try-convert/issues/463

**Comment by KC-MarKamp** [comment]
On it.

**Comment by KC-MarKamp** [comment]
Directly commited them to the master branch, see the last 13 commits to this branch.
