### ISSUE TITLE
Merging two addins into a single tab

### ISSUE THREAD

**Issue by dorschreier** [CAD-Booster/solidworks-api#31]
I'm currently working on a project where I'm utilizing two separate SolidWorks add-ins. However, I would love to consolidate the two add-ins into a single tab for ease of access and overall efficiency.

is there any way to do that with the Cad-Booster/SolidDna library's ?

I thank you all in advance for your help and advice.

Best regards,
[Your Name]

**Comment by brinkdinges** [comment]
What do you mean exactly? You can always combine the functionality of two add-ins into one, with or without SolidDna. 

If you're talking about toolbars, I think you should always be able to add a button to an existing toolbar. I don't know if that's supported by SolidDna, the CommandManager code needs some more work.
