### ISSUE TITLE
Fix CommandManager menu

### ISSUE THREAD

**Issue by KC-MarKamp** [CAD-Booster/solidworks-api#33]
- [x] It seems to remember toolbar settings, so if you run it twice, only some things are set as you ask, which isn't consistent.
- [x] The code is hard to understand
- [x] The terms are hard to understand
- [x] ~~CommandManagerItem has three boolean properties like VisibleForAssemblies. Can we combine these to use the single ModelTypes property in the methods to add the items~~ Let's keep is this way.
- [x] It uses integers for IDs and styles, which can be confusing.
- [x] Style is the same as TabView? Yes
- [x] swCommandTabButtonFlyoutStyle_e and swCommandTabButtonTextDisplay_e are combined in CommandManagerGroup.AddItemsToTab is weird, but it looks like that is meant to happen.

**Comment by brinkdinges** [comment]
I figured out why the list of styles uses integers, it's because it mixes values of two enums:

- CommandManagerItemTabView: values 0, 1, 2, 4
- swCommandTabButtonFlyoutStyle_e: values 8, 16, 32

**Comment by brinkdinges** [comment]
@KC-MarKamp Let's create an internal enum for the style that combines those two enums.

**Comment by KC-MarKamp** [comment]
@brinkdinges Fixed subtask 7 (_swCommandTabButtonFlyoutStyle_e and swCommandTabButtonTextDisplay_e are combined in CommandManagerGroup.AddItemsToTab is weird, but it looks like that is meant to happen.)_ with commit: 4b3054dabbdba90d60d3d72a2c90c9ff700733f8. Created the internal enum you've mentioned and created a struct for it to combine the ID and this newly created enum.
