### ISSUE TITLE
Load Two AddIns at same time

### ISSUE THREAD

**Issue by RPS-C** [CAD-Booster/solidworks-api#47]
Now,I have two solutions.First use angix solidna,second use this soliddna.Can load two addins at same time.

**Comment by brinkdinges** [comment]
AngelSix.SolidDNA was not designed to support two add-ins simultaneously, which is why we forked it and improved it. CADBooster.SolidDNA does support running two add-ins at the same time. So it doesn't surprise me that you cannot run one of each.
